"""init

Revision ID: fcabe49df597
Revises: 
Create Date: 2022-08-05 18:12:00.211119

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "fcabe49df597"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "characters",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("object_link", sa.String(), nullable=True),
        sa.Column("character_image", sa.String(), nullable=True),
        sa.Column(
            "character_class",
            sa.Enum(
                "berserk",
                "medic",
                "guardian",
                "specialist",
                "marksman",
                name="characterclassenum",
            ),
            nullable=True,
        ),
        sa.Column("description", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_characters")),
    )
    op.create_index(op.f("ix_characters_id"), "characters", ["id"], unique=False)
    op.create_index(op.f("ix_characters_name"), "characters", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_characters_name"), table_name="characters")
    op.drop_index(op.f("ix_characters_id"), table_name="characters")
    op.drop_table("characters")
    # ### end Alembic commands ###
